### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by waldyrious** [csonto/git-private#2]
I'm a little confused at this:

> Push to the default private space, named "junk":
>
>     git private-push master

I can't seem to make it work:

```
$ echo "foo bar" > somefile.txt

$ git checkout -b test-branch

$ git add somefile.txt

$ git commit -m "testing git-private"
  [test-branch 61ee021] testing git-private
   1 file changed, 1 insertion(+)

$ git private-push test-branch
  fatal: 'junk' does not appear to be a git repository
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.

$ git private-push test-branch origin
  fatal: 'junk' does not appear to be a git repository
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.

$ git private-push --id test-branch-remote test-branch origin
  fatal: 'test-remote' does not appear to be a git repository
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.

$ git private-push test-branch-remote origin
  error: src refspec test-branch-remote does not match any.
  error: failed to push some refs to 'junk'
```

What am I missing?

**Comment by csonto** [comment]
You should set remote - see https://github.com/csonto/git-private#configuration, for example, setting remote:

1. only for default "junk" space in the repo: `git configure --global private.junk.remote origin`
2. default for all private branches in a working directory: `git configure private.remote origin` (still can be overridden by above.)
3. global default for all private branches: `git configure --global private.remote origin`.

Or add a remote: `git remote add junk URL`.

I will make it clearer from README.

**Comment by csonto** [comment]
I have added a ["Configure private branches"](https://github.com/csonto/git-private#configure-private-branches) section to the README file.
